### ISSUE TITLE
Using a custom project to test ESGF publishing without RabbitMQ

### ISSUE THREAD

**Issue by anikfal** [ESGF/esg-publisher#259]
Hi. My ESGF Kubernetes deployment is up and running, and I'm now testing the publishing workflow:

1. Downloaded a CMIP6 file
2. Made it available via THREDDS
3. Generated the corresponding mapfiles

At this stage, I’m simply aiming to test the publishing pipeline with a sample dataset. Would CMIP6 data be suitable for this purpose, or would you recommend using a different dataset? This deployment is not intended to serve CMIP6 data in production, but rather other NetCDF datasets that are not part of any existing ESGF projects.

I’d like to create a custom project configuration to bypass the RabbitMQ password issue. However, modifying the project name in the `.ini` file from `cmip6` to `cmip6detect` results in the following errors:
```
(esgf-publish) [rocky@detectcontroller mapfile]$ esgpublish --map cmip6detect.C4MIP.NOAA-GFDL.GFDL-ESM4.1pctCO2-bgc.r1i1p1f1.Amon.ps.gr1.v20250602.map 
2025-06-11 12:07:16 WARNING  User project config missing or could not be parsed.
2025-06-11 12:07:16 INFO     No Globus UUID defined.
2025-06-11 12:07:16 ERROR    Project cmip6detect not supported.
Open an issue on our github to request additional project support.
```
Here is the content of my `~/.esg/esg.yaml` file:
```
data_node: esgf.jsc.fz-juelich.de
index_node: esgf.jsc.fz-juelich.de

data_roots:
  /test_data/badc/cmip6/data/CMIP6: cmip6detect

project: cmip6detect
cmor_path: /home/rocky/publishing/cmip6-cmor-tables/Tables

silent: false
skip_prepare: true
force_prepare: false
test: true

pid_creds:
  dummy.local:
    user: dummy
    password: dummy
    port: 5672
    priority: 1
    ssl_enabled: false
    vhost: dummy
```

**Comment by sashakames** [comment]
Hi, you'll need to define a section for the project and also specify that project "clones" CMIP6.  However, leave out the PID section and it will skip RabbitMQ.  Example:

```
user_project_config:
  cmip6plus:
    CONST_ATTR:
      project: CMIP6Plus
#    pid_prefix: '21.14100'  We comment out....
cmip6_clone: cmip6plus
```
