### ISSUE TITLE
Nginx Ingress not serving HARICA certificate – defaults to fake certificate

### ISSUE THREAD

**Issue by anikfal** [ESGF/esg-publisher#261]
My ESGF cluster, along with its components such as the LoadBalancer and Ingress, was up and running and accessible via HTTP. However, I’m currently facing issues setting up the same cluster to work over HTTPS.

I’ve already obtained the HARICA certificate and created the corresponding TLS secret:
```console
[rocky@detectcontroller ~]$ kubectl describe secret esgf-jsc-cert -n esgf
Name:         esgf-jsc-cert
Namespace:    esgf
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  2493 bytes
tls.key:  1704 bytes
```
However, the Ingress controller is not using the HARICA certificate and is instead falling back to the `default-fake-certificate`:
```console
[rocky@detectcontroller ~]$ kubectl exec -n ingress-nginx ingress-nginx-controller-6ccf95b469-k545r -- cat /etc/nginx/nginx.conf | grep -i ssl_certificate
	ssl_certificate     /etc/ingress-controller/ssl/default-fake-certificate.pem;
	ssl_certificate_key /etc/ingress-controller/ssl/default-fake-certificate.pem;
		ssl_certificate_by_lua_file /etc/nginx/lua/nginx/ngx_conf_certificate.lua;
		ssl_certificate_by_lua_file /etc/nginx/lua/nginx/ngx_conf_certificate.lua;
```
-----
Here's my ingress status:
```console
[rocky@detectcontroller ~]$ kubectl describe ingress esgf-ingress -n esgf
Name:             esgf-ingress
Labels:           app.kubernetes.io/component=ingress
                  app.kubernetes.io/instance=esgf
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=esgf
                  helm.sh/chart=esgf-0.1.0
Namespace:        esgf
Address:          134.94.199.72
Ingress Class:    nginx
Default backend:  <default>
TLS:
  esgf-jsc-cert terminates esgf.jsc.fz-juelich.de
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  esgf.jsc.fz-juelich.de  
                          /thredds                         esgf-thredds:8080 (10.10.127.207:8080)
                          /thredds/fileServer              esgf-file-server:8080 (10.10.127.202:8080)
                          /solr/aggregations/replication   esgf-solr-slave:8983 (10.10.127.205:8983)
                          /solr/datasets/replication       esgf-solr-slave:8983 (10.10.127.205:8983)
                          /solr/files/replication          esgf-solr-slave:8983 (10.10.127.205:8983)
                          /esg-search                      esgf-search:8080 (10.10.127.208:8080)
Annotations:              meta.helm.sh/release-name: esgf
                          meta.helm.sh/release-namespace: esgf
                          nginx.ingress.kubernetes.io/force-ssl-redirect: true
                          reloaded-at: 1750927716
Events:                   <none>
```
and Ingress block from `values.yaml`:
```yaml
ingress:
  # The annotations for the ingress
  # Depending on your Kubernetes cluster, this can be used to configure things like Let's Encrypt certificates
  ingressClassName: nginx
  annotations:
    #  cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # Extra labels to apply to the ingress resources
  labels: {}
  # Sign-in URL for unauthenticated requests
  authSignin:
  # TLS configuration
  tls:
    enabled: true
    # Either give the name of an existing TLS secret
    # See https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
    secretName: esgf-jsc-cert
    # Or provide a PEM-encoded certificate (including chain) and key as variables
    pem:
      cert:
      key:
    # If neither are given, then a self-signed certificate is generated
```
-----
Could you please explain how NGINX can be configured to serve my HARICA certificate?
